model: Adapnet
phase: train
data:
 data_size: [384, 512]
 directory: /home/ashutosh/Documents/mt_code/datasets/Gator_384_height_768_width_train_data_split/depth
 tfrecord:
  directory: ./tf_datasets/depth
  train_filename: freiburg-train-depth.tfrecords
  val_filename: freiburg-val-depth.tfrecords
  # test_filename: freiburg-test-rgb.tfrecords
  # all images should be in png format i.e the images and their labels as well
 classes:
  road: [255,255,255]
  background: [0,0,0]
data_processing:
 whitening: false
 random_crop: false
 max_crop: 32
 crop_height: 256
 crop_width: 256
 horizontal_flip: false
 vertical_flip: false
 brightness: false
 rotation: false
 all_augmentation: false
 random_augmentation: false
training_setting:
 analyse_lr: false
 epochs: 300
 batch_size: 7
 class_balancing: none
 padding_scheme: caffe
 save_visualization_image: true
 logging:
  display_iteration: 210
  evaluation_iteration: 210
  training_note: "depth----run with resolution-384,512 and (981, 105 train datasplit)"
 checkpoints:
  save_directory: ./checkpoints
  prefix: "adapnet"
  save_step: 210
 loss: cross_entropy
 optimizer: Adam
 learning_rate: 0.001
 lr_mult: 1
 lr_mult_bias: 2
 cyclic_learning_rate:
  type: ""
  additional_setting: ""
 weight_decay: 5e4
 clip_norm: 1.0
testing_setting:
 batch_size: 32





